import type {Metadata} from 'next'
import {Inter} from 'next/font/google'

import '@dreipol/t3-ui/lib/bundle.css'
import '@dreipol/t3-react-theme/lib/bundle.css'

import './globals.css'
import {getServerSession} from "next-auth";
import {SessionData} from "googleapis-common/build/src/http2";
import {redirect} from "next/navigation";
import {Providers} from "../lib/components/providers";
import {authOptions} from '../lib/auth-options'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {
    // @ts-ignore
    const session = (await getServerSession(authOptions)) as SessionData;

    if (!session) {
        return redirect('/api/auth/signin');
    }

    return (
        <html lang="en">
        <body className={inter.className}>
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    )
}
